#!/usr/bin/env sh

set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
JSON_FILE="${ROOT_DIR}/json.json"
OUTPUT_FILE="${ROOT_DIR}/readme.md"
TMP_FILE="${OUTPUT_FILE}.tmp"

BASE_URL="https://www.instant-gaming.com"
LOCALE="${LOCALE:-fr}"
REFERRAL="jaha"
AUTO_SCRIPT_URL="https://github.com/enzomtpYT/InstantGaming-Giveaway-AutoParticipate"

if ! command -v jq >/dev/null 2>&1; then
	echo "Error: jq is required but was not found in PATH." >&2
	exit 1
fi

if [ ! -f "$JSON_FILE" ]; then
	echo "Error: missing file $JSON_FILE" >&2
	exit 1
fi

alive_count="$(jq '.alive | length' "$JSON_FILE")"
dead_count="$(jq '.dead | length' "$JSON_FILE")"

{
	echo "# InstantGaming's Giveaway List"
	echo
	echo "## Navigation"
	echo
	echo "- [Quick Start](#quick-start)"
	echo "- [Overview](#overview)"
	echo "- [Active Giveaways](#active-giveaways)"
	echo "- [Inactive Giveaways](#inactive-giveaways)"
	echo "- [Automation](#automation)"
	echo
	echo "## Quick Start"
	echo
	echo "1. Open an Instant Gaming account."
	echo "2. Go to [Active Giveaways](#active-giveaways)."
	echo "3. Open each link and follow the on-site participation steps."
	echo
	echo "## Overview"
	echo
	echo "| Section | Count |"
	echo "| --- | ---: |"
	echo "| Active giveaways | ${alive_count} |"
	echo "| Inactive giveaways | ${dead_count} |"
	echo
	echo "## Active Giveaways"
	echo
	echo "Use these links to participate manually."
	echo
	echo "<details open>"
	echo "<summary><strong>Show active giveaway links (${alive_count})</strong></summary>"
	echo
	echo
	jq -r --arg base "$BASE_URL" --arg locale "$LOCALE" --arg ref "$REFERRAL" '
		.alive[] | "- [\(.)](\($base)/\($locale)/giveaway/\(.)?igr=\($ref))"
	' "$JSON_FILE"
	echo
	echo "</details>"
	echo
	echo "## Inactive Giveaways"
	echo
	echo "These links are kept for archive/reference and may no longer be valid."
	echo
	echo "<details>"
	echo "<summary><strong>Show inactive giveaway links (${dead_count})</strong></summary>"
	echo
	jq -r --arg base "$BASE_URL" --arg locale "$LOCALE" --arg ref "$REFERRAL" '
		.dead[] | "- [\(.)](\($base)/\($locale)/giveaway/\(.)?igr=\($ref))"
	' "$JSON_FILE"
	echo
	echo "</details>"
	echo
	echo "## Automation"
	echo
	echo "Prefer automatic participation? Install [this userscript](${AUTO_SCRIPT_URL})."
	echo
	echo "## How to Regenerate This README"
	echo
	echo "### Prerequisites"
	echo
	echo "- A POSIX-compatible shell (bash, dash, zsh, etc.)"
	echo "- [jq](https://stedolan.github.io/jq/) installed and available in PATH"
	echo
	echo "### Quick Usage"
	echo
	echo "Run the generator from the repository root:"
	echo
	echo "\`\`\`sh"
	echo "./misc/generateReadme.sh"
	echo "\`\`\`"
	echo
	echo "The script reads [json.json](json.json) and overwrites [readme.md](readme.md) only when content changes."
	echo
	echo "### Configuration (Environment Variables)"
	echo
	echo "| Variable | Default | Description |"
	echo "| --- | --- | --- |"
	echo "| \`LOCALE\` | \`fr\` | Locale path segment (e.g., \`fr\`, \`en\`, \`de\`) |"
	echo
	echo "Example with custom locale:"
	echo
	echo "\`\`\`sh"
	echo "LOCALE=en ./misc/generateReadme.sh"
	echo "\`\`\`"
	echo
	echo "### GitHub Actions Automation"
	echo
	echo "This repository includes a workflow ([.github/workflows/generateReadme.yml](.github/workflows/generateReadme.yml)) that automatically regenerates the README when:"
	echo
	echo "- \`json.json\` is updated"
	echo "- \`misc/generateReadme.sh\` is modified"
	echo "- The workflow file itself changes"
	echo
	echo "You can also trigger it manually via the \"Actions\" tab → \"Generate Optimized README\" → \"Run workflow\"."
	echo
	echo "---"
	echo
	echo "Generated by [misc/generateReadme.sh](misc/generateReadme.sh)."
} >"$TMP_FILE"

if [ -f "$OUTPUT_FILE" ] && cmp -s "$TMP_FILE" "$OUTPUT_FILE"; then
	rm -f "$TMP_FILE"
	echo "No changes in $OUTPUT_FILE"
	exit 0
fi

mv "$TMP_FILE" "$OUTPUT_FILE"
echo "Updated $OUTPUT_FILE"
